version: '3'

services:

  assetDb:
    image: 'postgres:13.1-alpine'
    container_name: assetDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks : 
      - impact-net

  impactDb:
    image: 'postgres:13.1-alpine'
    container_name: impactDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks : 
      - impact-net

  assetapp:
    image: 'daniel9917/asset-management-service-test:latest'
    # build:
    #   context: .
    container_name: assetapp
    depends_on:
      - assetDb
      - impactapp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://assetDb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - IMPACT_URL=http://impactapp:8081
    ports:
      - "8080:8080"
    networks : 
      - impact-net
    restart : always

  impactapp:
    image: 'daniel9917/impact-service-test:latest'
    # build:
    #   context: .
    container_name: impactapp
    depends_on:
      - impactDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://impactDb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    networks : 
      - impact-net
    restart : always

networks:
  impact-net :
    driver : bridge
